### ISSUE TITLE
ScenePath was wrong

### ISSUE THREAD

**Issue by bettercalljason** [Marcotrombino/FXRouter#1]
Hi, I got a InvocationTargetException because scenePath looked like this:
/com.example.path/sample.xml 
but it had to be
/com/example/path/sample.xml

So I simply replaced the dots with forward slashes in pathRef.

I hope this helps somebody.

**Comment by Marcotrombino** [comment]
Thanks for contributing, dot notation is just a namespace convention for the directory path. Being a .fxml file you have to pass the path with slashes notation.
